server:
  port: 8888

spring:
  application:
    name: jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.89:3306/test_zh?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: vzp-admin
    password: jZoq9Tl2OzP48Z1V
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
